/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description status=ok/db=ok if a SELECT 1 round-trips; status=degraded/db=error
         *     (HTTP 503) if the DB ping fails -- the process itself is still up and
         *     able to answer this request either way.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Config
         * @description Returns business_legal_name/business_short_name + which payment
         *     methods (stripe/paypal/zelle) are currently configured. Builds a
         *     fresh AppConfig per request (not a module-level singleton) so tests
         *     that monkeypatch env vars at request time are honored, same pattern
         *     as logand.app's api/invoices.py routes.
         */
        get: operations["get_public_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Validates credentials, mints a session, sets the __Host-session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the current session and clears the cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Returns the current admin session's identity.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description GET /api/courses -- active courses w/ card fields.
         */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course
         * @description GET /api/courses/{slug} -- full course detail.
         */
        get: operations["get_course_api_courses__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{slug}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Course Sessions
         * @description GET /api/courses/{slug}/sessions -- published+full future sessions.
         */
        get: operations["list_course_sessions_api_courses__slug__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Booking Endpoint
         * @description POST /api/bookings -- rate-limited 5/hour, honeypot-checked.
         */
        post: operations["create_booking_endpoint_api_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Waitlist Endpoint
         * @description POST /api/bookings/waitlist -- same shape minus payment.
         */
        post: operations["join_waitlist_endpoint_api_bookings_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/manage/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Booking By Token Endpoint
         * @description GET /api/bookings/manage/{token} -- rate-limited 30/hour.
         */
        get: operations["get_booking_by_token_endpoint_api_bookings_manage__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/manage/{token}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Booking By Token Endpoint
         * @description POST /api/bookings/manage/{token}/cancel.
         */
        post: operations["cancel_booking_by_token_endpoint_api_bookings_manage__token__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/manage/{token}/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Confirmation Endpoint
         * @description POST /api/bookings/manage/{token}/resend-confirmation.
         */
        post: operations["resend_confirmation_endpoint_api_bookings_manage__token__resend_confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invoices/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Aggregate invoice/payment/refund stats for the admin dashboard --
         *     thin wrapper over domain/invoices/stats.py. Declared BEFORE the
         *     /{invoice_id} routes so FastAPI never tries to parse "stats" as an
         *     invoice id.
         */
        get: operations["get_stats_api_admin_invoices_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description Admin invoice listing (most recent first).
         */
        get: operations["list_invoices_api_admin_invoices_get"];
        put?: never;
        /**
         * Create Invoice Endpoint
         * @description Admin creates a new draft invoice.
         */
        post: operations["create_invoice_endpoint_api_admin_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invoices/{invoice_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Invoice
         * @description Admin sends (or re-sends) the invoice email -- flips draft ->
         *     sent (idempotent for an already-sent invoice) and emails the
         *     pay-by-link URL. The link is the invoice's one stable derived token
         *     (see derive_pay_token / pay_link_for_invoice), so a re-send carries
         *     the SAME URL as the original -- nothing is invalidated by
         *     re-sending.
         */
        post: operations["send_invoice_api_admin_invoices__invoice_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invoices/{invoice_id}/manual-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Manual Payment Endpoint
         * @description Admin records a Zelle/cash/card-reader-outside-the-system payment.
         */
        post: operations["record_manual_payment_endpoint_api_admin_invoices__invoice_id__manual_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invoices/{invoice_id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund Payment Endpoint
         * @description Admin-only (not staff -- see docs/design/02's authorization model).
         */
        post: operations["refund_payment_endpoint_api_admin_invoices__invoice_id__refund_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sessions/{class_session_id}/invoice-unpaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invoice Unpaid For Session
         * @description "Invoice everyone still unpaid for Saturday's class" -- creates one
         *     invoice per confirmed booking on the session that has no invoice_id
         *     yet, skipping already-invoiced bookings.
         */
        post: operations["invoice_unpaid_for_session_api_admin_sessions__class_session_id__invoice_unpaid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pay/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice Status
         * @description GET /api/pay/{token} -- pay page data: amount due + configured
         *     payment methods. Token invalid -> 404 (never confirms existence).
         */
        get: operations["get_invoice_status_api_pay__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pay/{token}/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Payment Methods
         * @description POST /api/pay/{token}/payment-methods -- availability check scoped
         *     to a real invoice token (still 404s an invalid token, unlike the
         *     unauthenticated GET /api/config, which is deliberately fine to leak
         *     global availability but not per-invoice existence).
         */
        post: operations["check_payment_methods_api_pay__token__payment_methods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pay/{token}/stripe-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stripe Intent
         * @description Creates a Stripe PaymentIntent for this invoice's remaining
         *     balance. The webhook (api/webhooks.py), not this endpoint, is what
         *     records the Payment row and settles the invoice -- this only ever
         *     hands back a client_secret for the frontend to confirm against.
         *
         *     Row-locked + idempotent-reuse (CRIB: logand.app's pay_invoice): the
         *     lock serializes concurrent requests against the SAME invoice, and a
         *     still-live existing intent is reused rather than re-created -- Stripe
         *     would happily create as many PaymentIntents as asked, and a guest
         *     confirming two of them (double-clicked pay button, two open tabs)
         *     would really be charged twice for one invoice.
         */
        post: operations["create_stripe_intent_api_pay__token__stripe_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pay/{token}/paypal-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Paypal Order Endpoint
         * @description Creates a PayPal order for this invoice's remaining balance.
         */
        post: operations["create_paypal_order_endpoint_api_pay__token__paypal_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pay/{token}/paypal-order/{order_id}/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture Paypal Order Endpoint
         * @description Captures an approved PayPal order and records the resulting
         *     Payment -- rejects a capture whose reference_id doesn't match THIS
         *     invoice (see paypal.PayPalCapture's own doc comment: never trust the
         *     client-supplied order_id belongs to the invoice URL it was posted
         *     to).
         */
        post: operations["capture_paypal_order_endpoint_api_pay__token__paypal_order__order_id__capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Verifies the Stripe signature, then handles payment_intent.succeeded/
         *     .payment_failed idempotently. NOTE: no session/CSRF auth here by
         *     design -- Stripe signature verification IS the auth for this route
         *     (see app/app.py's CSRF-exempt prefix list); do not add require_admin
         *     or csrf checks.
         */
        post: operations["stripe_webhook_api_webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedule/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses Admin
         * @description Admin course listing, including inactive courses.
         */
        get: operations["list_courses_admin_api_admin_schedule_courses_get"];
        put?: never;
        /**
         * Create Course
         * @description Admin creates a new course.
         */
        post: operations["create_course_api_admin_schedule_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedule/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Admin schedules a new session for a course.
         */
        post: operations["create_session_api_admin_schedule_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedule/sessions/{class_session_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Session
         * @description Admin publishes a draft session.
         */
        post: operations["publish_session_api_admin_schedule_sessions__class_session_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedule/sessions/{class_session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Session
         * @description Admin cancels a session, cascading notification emails (REQUIRED).
         */
        post: operations["cancel_session_api_admin_schedule_sessions__class_session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedule/sessions/{class_session_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Roster
         * @description Admin roster listing for a session.
         */
        get: operations["get_session_roster_api_admin_schedule_sessions__class_session_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedule/bookings/on-behalf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create On Behalf Booking
         * @description Phone bookings: Mel types what the caller says; skips rate limits,
         *     records attestation_version='admin-phone'.
         */
        post: operations["create_on_behalf_booking_api_admin_schedule_bookings_on_behalf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Students
         * @description Admin student roster listing.
         */
        get: operations["list_students_api_admin_students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Student
         * @description Admin student detail.
         */
        get: operations["get_student_api_admin_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{student_id}/bookings/{booking_id}/mark-attended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Attended
         * @description Admin roster bookkeeping: confirmed -> attended.
         */
        post: operations["mark_attended_api_admin_students__student_id__bookings__booking_id__mark_attended_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{student_id}/bookings/{booking_id}/mark-no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark No Show
         * @description Admin roster bookkeeping: confirmed -> no_show.
         */
        post: operations["mark_no_show_api_admin_students__student_id__bookings__booking_id__mark_no_show_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/waivers/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Waivers
         * @description Admin lists every waiver on file for a student.
         */
        get: operations["list_waivers_api_admin_waivers_students__student_id__get"];
        put?: never;
        /**
         * Upload Waiver Endpoint
         * @description Admin uploads a waiver scan for a student -- allowlisted content types only.
         */
        post: operations["upload_waiver_endpoint_api_admin_waivers_students__student_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/waivers/{waiver_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Waiver
         * @description Streams a waiver's bytes through this authenticated route -- never
         *     a public URL, see docs/design/13-storage-abstraction.md.
         */
        get: operations["download_waiver_api_admin_waivers__waiver_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttestationInput
         * @description The eligibility attestation the booker agreed to (see doc 06).
         */
        AttestationInput: {
            /**
             * Version
             * @default
             */
            version: string;
            /**
             * Accepted
             * @default false
             */
            accepted: boolean;
        };
        /** Body_upload_waiver_endpoint_api_admin_waivers_students__student_id__post */
        Body_upload_waiver_endpoint_api_admin_waivers_students__student_id__post: {
            /** File */
            file: string;
        };
        /**
         * BookingCreateRequest
         * @description Guest booking form -- session_id, contact info, party_size,
         *     attestation, sms_consent, and a honeypot field bots fill but humans
         *     never see.
         */
        BookingCreateRequest: {
            /** Session Id */
            session_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone */
            phone?: string | null;
            /**
             * Party Size
             * @default 1
             */
            party_size: number;
            /**
             * @default {
             *       "version": "",
             *       "accepted": false
             *     }
             */
            attestation: components["schemas"]["AttestationInput"];
            /**
             * Sms Consent
             * @default false
             */
            sms_consent: boolean;
            /**
             * Honeypot Field
             * @default
             */
            honeypot_field: string;
        };
        /**
         * CourseCard
         * @description Card-length course fields for the catalog grid.
         */
        CourseCard: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Price */
            price: string;
            /** Deposit */
            deposit: string;
            /** Duration Min */
            duration_min: number;
        };
        /**
         * CourseDetail
         * @description Full course detail (adds the long-form markdown description).
         */
        CourseDetail: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Price */
            price: string;
            /** Deposit */
            deposit: string;
            /** Duration Min */
            duration_min: number;
            /** Description */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness + DB-reachability probe payload.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
        };
        /**
         * InvoiceCreateRequest
         * @description Admin's new-invoice form.
         */
        InvoiceCreateRequest: {
            /** Student Id */
            student_id: string;
            /** Line Items */
            line_items: components["schemas"]["LineItemRequest"][];
            /** Memo */
            memo?: string | null;
        };
        /**
         * LineItemRequest
         * @description One line item on a create-invoice request.
         */
        LineItemRequest: {
            /** Description */
            description: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number | string;
            /** Unit Price */
            unit_price: number | string;
            /** Unit */
            unit?: string | null;
        };
        /**
         * LoginRequest
         * @description Admin login form fields.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ManualPaymentRequest
         * @description Admin's manual-payment form.
         */
        ManualPaymentRequest: {
            /**
             * Method
             * @enum {string}
             */
            method: "paypal" | "zelle" | "in_person" | "other";
            /** Amount */
            amount: number | string;
            /** Note */
            note?: string | null;
        };
        /**
         * MeResponse
         * @description The current admin session's identity.
         */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Role */
            role: string;
        };
        /**
         * PaymentMethods
         * @description Which payment surfaces are currently configured -- the frontend
         *     hides a method entirely rather than showing a disabled button when
         *     its backing config is unset (docs/design/05).
         */
        PaymentMethods: {
            /** Stripe */
            stripe: boolean;
            /** Paypal */
            paypal: boolean;
            /** Zelle Handle */
            zelle_handle: string | null;
        };
        /**
         * PublicConfigResponse
         * @description Public-safe brand + payment-method availability, sourced entirely
         *     from AppConfig -- no secrets, no DB hit needed.
         */
        PublicConfigResponse: {
            /** Business Legal Name */
            business_legal_name: string;
            /** Business Short Name */
            business_short_name: string;
            payment_methods: components["schemas"]["PaymentMethods"];
        };
        /**
         * RefundRequest
         * @description Admin's refund form -- client_request_id is REQUIRED (see
         *     domain/invoices/refunds.py's own doc comment on why).
         */
        RefundRequest: {
            /** Payment Id */
            payment_id: string;
            /** Amount */
            amount?: number | string | null;
            /** Reason */
            reason?: string | null;
            /** Client Request Id */
            client_request_id: string;
        };
        /**
         * SessionCard
         * @description A bookable session with seats-left in machine-usable form (the UI
         *     renders "N of M seats open" in plain words).
         */
        SessionCard: {
            /** Id */
            id: string;
            /** Course Id */
            course_id: string;
            /** Starts At */
            starts_at: string;
            /** Ends At */
            ends_at: string;
            /** Location Name */
            location_name: string;
            /** Location Addr */
            location_addr: string;
            /** Capacity */
            capacity: number;
            /** Seats Open */
            seats_open: number;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_public_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfigResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseCard"][];
                };
            };
        };
    };
    get_course_api_courses__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_sessions_api_courses__slug__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_endpoint_api_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_waitlist_endpoint_api_bookings_waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_by_token_endpoint_api_bookings_manage__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_by_token_endpoint_api_bookings_manage__token__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_confirmation_endpoint_api_bookings_manage__token__resend_confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_admin_invoices_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_admin_invoices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoice_endpoint_api_admin_invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_invoice_api_admin_invoices__invoice_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_manual_payment_endpoint_api_admin_invoices__invoice_id__manual_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refund_payment_endpoint_api_admin_invoices__invoice_id__refund_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_unpaid_for_session_api_admin_sessions__class_session_id__invoice_unpaid_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_session_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_status_api_pay__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_payment_methods_api_pay__token__payment_methods_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stripe_intent_api_pay__token__stripe_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_paypal_order_endpoint_api_pay__token__paypal_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_paypal_order_endpoint_api_pay__token__paypal_order__order_id__capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_api_webhooks_stripe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_courses_admin_api_admin_schedule_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_course_api_admin_schedule_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_admin_schedule_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_session_api_admin_schedule_sessions__class_session_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_session_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_session_api_admin_schedule_sessions__class_session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_session_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_roster_api_admin_schedule_sessions__class_session_id__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_session_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_on_behalf_booking_api_admin_schedule_bookings_on_behalf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_api_admin_students_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_api_admin_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_attended_api_admin_students__student_id__bookings__booking_id__mark_attended_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
                booking_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_no_show_api_admin_students__student_id__bookings__booking_id__mark_no_show_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
                booking_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_waivers_api_admin_waivers_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_waiver_endpoint_api_admin_waivers_students__student_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_waiver_endpoint_api_admin_waivers_students__student_id__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_waiver_api_admin_waivers__waiver_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waiver_id: string;
            };
            cookie?: {
                "__Host-session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
