// GENERATED by `make types` (openapi-typescript against
// ../backend/openapi.json) -- see docs/design/07-frontend-architecture.md.
// DO NOT EDIT BY HAND. This placeholder exists only so imports of this
// module typecheck before the backend's OpenAPI spec exists to generate
// against for real.

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface paths {}
